version: "3.9"

services:
  backend:
    build:
      context: ./app/backend
    container_name: palaemon-backend
    network_mode: "host"
    volumes:
      - ./app/backend:/app
      - /usr/bin/tailscale:/usr/bin/tailscale
      - /var/run/tailscale:/var/run/tailscale
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./app/frontend
    container_name: palaemon-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
